jwt:
  secret: '[a-zA-Z0-9._]^+$Guidelines89797987forAlphabeticalArraNumeralsandotherSymbol$'

#server:
#  port: 8080
issuer-uri: http://localhost:8080/auth

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/projectmanagement
    password: Prince@9123
    username: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

  mvc:
    throw-exception-if-no-handler-found: true
    resources:
      add-mappings: false